### PR TITLE
Feature: send email with template

### PR DESCRIPTION
**Pull request by arbfay**
Introduced the `TemplateModel` struct which only makes it possible to either use it directly, convert from a `HashMap`, a `BTreeMap` and an `IndexMap` with the new introduced feature `indexmap`. The reason we need `TemplateModel` is because the model can be a nested JSON, which require extra steps for theuser if they were to manage the conversion themselves.﻿

### CODE REVIEW

**Comment by arbfay** [comment]
@pastjean what do you think?

**Review by pastjean — COMMENTED** [review]
This is great, i wonder if adding indexmap is worth it or should be let to users that need to use it and keep the dependency list low.

Also I see you added `uuid`  as and optional feature crate but it's not used anywhere.

**Comment by arbfay** [comment]
sorry about `uuid`, that was an experiment. For `indexmap`, this is totally optional. I think it's common for crates to support additional, non-std data types through features. IndexMap is what I use as it is better supported by `rkyv`, and it's also a very popular map (~50M downloads).

**Review by pastjean — APPROVED** [review]

**Comment by pastjean** [comment]
I've tweaked a little, replaced new with default + fixed the lint. I am releasing the new version as I write this.

https://crates.io/crates/postmark with version 0.5.0

**Comment by arbfay** [comment]
Thanks! I will try to contribute more as my needs expand 😸

**Pull request merged**
